openapi: 3.1.0
info:
  title: Lane Universal ACP Adapter (Demo)
  version: "1.0.0"
  description: >
    Product feed and checkout session API for Lane's demo.

servers:
  - url: https://acp-adapter-backend.onrender.com

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  parameters:
    IdempotencyKey:
      name: Idempotency-Key
      in: header
      required: false
      schema:
        type: string
    RequestId:
      name: Request-Id
      in: header
      required: false
      schema:
        type: string
    SessionId:
      name: session_id
      in: path
      required: true
      schema:
        type: string

  schemas:
    Product:
      type: object
      properties:
        product_id: { type: string }
        title: { type: string }
        price_minor: { type: integer, description: Price in minor units (e.g., cents) }
        currency: { type: string, default: USD }
        enable_checkout: { type: boolean }
        image_url: { type: string, format: uri, nullable: true }
        description: { type: string, nullable: true }
      required: [product_id, title, price_minor, currency, enable_checkout]

    ProductFeed:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Product'
      required: [items]

    Address:
      type: object
      properties:
        name: { type: string }
        line1: { type: string }
        line2: { type: string, nullable: true }
        city: { type: string }
        state: { type: string }
        postal_code: { type: string }
        country: { type: string, default: US }
      required: [name, line1, city, state, postal_code, country]

    Buyer:
      type: object
      properties:
        name: { type: string }
        email: { type: string, format: email }
      required: [email]

    LineItem:
      type: object
      properties:
        product_id: { type: string }
        quantity: { type: integer, minimum: 1, default: 1 }
      required: [product_id, quantity]

    CheckoutSession:
      type: object
      properties:
        id: { type: string }
        status: { type: string, enum: [draft, pending, completed, failed] }
        buyer: { $ref: '#/components/schemas/Buyer' }
        items:
          type: array
          items: { $ref: '#/components/schemas/LineItem' }
        fulfillment_address: { $ref: '#/components/schemas/Address' }
        subtotal_minor: { type: integer }
        shipping_minor: { type: integer }
        tax_minor: { type: integer }
        total_minor: { type: integer }
        currency: { type: string, default: USD }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }
      required: [id, status, items, currency]

    CheckoutSessionCreateRequest:
      type: object
      properties:
        buyer: { $ref: '#/components/schemas/Buyer' }
        items:
          type: array
          items: { $ref: '#/components/schemas/LineItem' }
          minItems: 1
        fulfillment_address: { $ref: '#/components/schemas/Address' }
        metadata:
          type: object
          additionalProperties: true
      required: [buyer, items]

    CheckoutSessionUpdateRequest:
      type: object
      properties:
        buyer: { $ref: '#/components/schemas/Buyer' }
        items:
          type: array
          items: { $ref: '#/components/schemas/LineItem' }
        fulfillment_address: { $ref: '#/components/schemas/Address' }
        metadata:
          type: object
          additionalProperties: true

    CheckoutSessionCompleteRequest:
      type: object
      properties:
        payment_method_id:
          type: string
          description: Demo/test identifier
        metadata:
          type: object
          additionalProperties: true
      required: [payment_method_id]

paths:
  /health:
    get:
      operationId: healthCheck
      summary: Health check
      responses:
        "200":
          description: OK

  /feed.json:
    get:
      operationId: getProductFeed
      summary: Fetch product feed
      security: [ { api_key: [] } ]
      responses:
        "200":
          description: Successful response with product feed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductFeed'

  /checkout_sessions:
    post:
      operationId: createCheckoutSession
      summary: Create a new checkout session
      security: [ { api_key: [] } ]
      parameters:
        - $ref: '#/components/parameters/IdempotencyKey'
        - $ref: '#/components/parameters/RequestId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckoutSessionCreateRequest'
      responses:
        "201":
          description: Checkout session created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckoutSession'

  /checkout_sessions/{session_id}:
    get:
      operationId: getCheckoutSession
      summary: Retrieve checkout session by ID
      security: [ { api_key: [] } ]
      parameters:
        - $ref: '#/components/parameters/SessionId'
      responses:
        "200":
          description: Checkout session data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckoutSession'

    post:
      operationId: updateCheckoutSession
      summary: Update a checkout session
      security: [ { api_key: [] } ]
      parameters:
        - $ref: '#/components/parameters/SessionId'
        - $ref: '#/components/parameters/IdempotencyKey'
        - $ref: '#/components/parameters/RequestId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckoutSessionUpdateRequest'
      responses:
        "200":
          description: Updated checkout session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckoutSession'

  /checkout_sessions/{session_id}/complete:
    post:
      operationId: completeCheckoutSession
      summary: Complete checkout session
      security: [ { api_key: [] } ]
      parameters:
        - $ref: '#/components/parameters/SessionId'
        - $ref: '#/components/parameters/IdempotencyKey'
        - $ref: '#/components/parameters/RequestId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckoutSessionCompleteRequest'
      responses:
        "200":
          description: Checkout completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckoutSession'
